---
- name: playbook_packages.yml - arch packages
  hosts: all
  become: yes

  tasks:
    # ARCH PACKAGES ---------------------------------------------------------------------------
    - name: install base packages
      pacman:
        update_cache: yes
        name:
          - android-file-transfer
          - android-tools
          - baobab
          - bat
          - blender
          - bluez
          - blueman
          - btop
          - celluloid
          - clamtk
          - dbeaver
          - diff-so-fancy
          - discord
          - dua-cli
          - eza
          - easyeffects
          - fd
          - fzf
          - galculator
          - gamemode
          - geeqie
          - gnome-disk-utility
          - gst-plugins-base
          - hyprland
          - kitty
          - kvantum
          - lazygit
          - libreoffice-still
          - lsp-plugins
          - lxappearance
          - mesa
          - mpv
          - navi
          - nemo
          - nemo-fileroller
          - nemo-image-converter
          - neofetch
          - neovide
          - neovim
          - npm
          - nm-connection-editor
          - nvtop
          - obsidian
          - onefetch
          - pavucontrol
          - pinta
          - polkit-gnome
          - ripgrep
          - ripgrep-all
          - scrcpy
          - sd
          - swappy
          - swaydile
          - thunderbird
          - ufw
          - waybar
          - wine
          - wl-clipboard
          - yt-dlp
          - yarn
          - xplr
          - zathura
          - zathura-pdf-mupdf

    # AUR PACKAGES ---------------------------------------------------------------------------
    - name: install aur packages
      kewlfft.aur.aur:
        name:
          - amf-amdgpu-pro
          - activitywatch-bin
          - adwsteamgtk
          - android-sdk-platform-tools
          - ani-cli
          - arronax
          - betterdiscord-installer-bin
          - brave-bin
          - catppuccin-gtk-macchiato
          - cava
          - cemu-bin
          - devify
          - downgrade
          - find-the-command
          - heroic-games-launcher
          - hyprpicker-git
          - hyprshot
          - lazynpm
          - librewolf-bin
          - ludusavi
          - mangal-bin
          - nerd-fonts-git
          - nwg-displays
          - nwg-look
          - obs-studio-amf
          - paccache-hook
          - pika-backup
          - pinterest-downloader-git
          - pipes.sh
          - prettierd
          - proton-ge-custom-bin
          - pyprland
          - spotdl
          - reflector-pacman-hook-git
          - rofi-lboon-wayland-git
          - rofi-file-browser-extended-git
          - scc-bin
          - sddm-git
          - shell-color-scripts
          - spicetify-cli
          - spotify
          - swaylock-effects
          - swaync
          - swayosd-git
          - swww
          - sysz
          - tgpt-bin
          - ttf-ms-win11-auto
          - tty-clock-git
          - unimatrix-git
          - upscayl-bin
          - vkbasalt
          - vulkan-amdgpu-pro
          - wev
          - wl-clip-persist-git
          - wleave-git
          - wlr-randr
          - wlrobs-hg
          - xdg-desktop-portal-hyprland-git
          - youtube-dl
          - ytdlp-gui
          - zarchive-git
