[pyprland]
plugins = ["scratchpads", "magnify", "wallpapers"]

[scratchpads.volume]
command = "pavucontrol"
unfocus = "hide"
position = "1% 8%"
lazy = true
force_monitor = "DP-1"

[scratchpads.terminal]
command = "kitty --class scratchpad-large"
lazy = true

[scratchpads.yazi]
command = "kitty --class scratchpad-large fish -c yazi"
unfocus = "hide"
hysteresis = 0.1
lazy = true

[scratchpads.gpt]
command = "kitty --class scratchpad-large tgpt -m"
lazy = true

[scratchpads.dots]
command = "kitty --class scratchpad-large yadm enter lazygit"
lazy = true

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.nvtop]
command = "kitty --class scratchpad-large nvtop"
lazy = true

[scratchpads.topgrade-system]
command = "kitty --class scratchpad-large fish -c 'up'"
lazy = true

[scratchpads.topgrade-all]
command = "kitty --class scratchpad-large fish -c 'upall'"
lazy = true

[scratchpads.bluetooth]
command = "overskride"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.wifi]
command = "iwgtk"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.network]
command = "nm-connection-editor"
animation = "fromRight"
margin = 20
lazy = true

[wallpapers]
path = "~/.config/hypr/theme/walls/"
interval = 60                                                                                                                                                                                               # change every hour
command = "swww img --transition-bezier 0.5,1.19,.8,.4 --transition-type wipe --transition-duration 2 --transition-fps 75 \"[file]\" && notify-send 'Wallpaper Changed' -i \"[file]\" --app-name=Wallpaper"
clear_command = "swww clear"
extensions = ["jpg", "png", "gif", "jpeg"]
