[tools]
usage = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
uv = "latest"
cargo-binstall = "latest"
age = "latest"
deno = "latest"
go = "latest"
watchexec = "latest"

# Cargo Tools
"cargo:cargo-cache" = "latest"
"cargo:kanata" = "latest"
"cargo:atac" = "latest"
"cargo:youtube-tui" = "latest"
"cargo:dedoc" = "latest"
"cargo:https://github.com/fioncat/otree" = "latest"

# Go Tools
"go:github.com/stefanlogue/meteor" = "latest"
"go:github.com/crumbyte/noxdir" = "latest"
"go:github.com/sahaj-b/wakafetch" = "latest"
"go:github.com/jbensmann/mouseless" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"go:github.com/boyter/scc/v3" = "latest"

# Python Tools
"pipx:darrenburns/posting" = "latest"
"pipx:pytest" = "latest"
"pipx:b2" = "latest"

# Node Tools
"npm:five-server" = "latest"
"npm:opencode-ai" = "latest"

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true # enabled by default (unlike asdf)

# configure `mise install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = ['~/dev']

verbose = false     # set to true to see full installation output, see `MISE_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false         # set to true to automatically answer yes to all prompts

not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
task_output = "prefix"        # see Tasks Runner for more information
paranoid = false              # see MISE_PARANOID

disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`

env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`

experimental = true # enable experimental features

# configure messages displayed when entering directories with config files
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
cargo_binstall = true                                                                            # Install pre-compiled cargo packages
pipx_uvx = true                                                                                  # Use uvx instead of pipx
idiomatic_version_file_enable_tools = ["node"]
npm.bun = true
